require:
  - rubocop-rake
  - rubocop-rspec
inherit_gem:
  sgcop: ruby/rubocop.yml

AllCops:
  NewCops: enable
Bundler/GemComment:
    Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/ReceiveMessages:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
