#!/usr/bin/env ruby

require_relative '../lib/copy_tuner_incompatible_search'

project_name = File.basename(Dir.pwd)
timestamp = Time.now.strftime('%Y%m%d%H%M%S')
output_path = "tmp/usages-#{project_name}-#{timestamp}.xlsx"
CopyTunerIncompatibleSearch::SearchCommand.run(output_path)
puts "open #{output_path}"
`open #{output_path}`
